-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2017-04-24 01:20:47.404

-- tables
-- Table: ACCOUNT
CREATE TABLE ACCOUNT (
    NAME nvarchar(max)  NULL,
    PASSWORD nvarchar(max)  NULL,
    FULLNAME nvarchar(max)  NULL,
    BIRTHDAY date  NOT NULL,
    EMAIL nvarchar(max)  NULL,
    PHONE nvarchar(max)  NULL,
    TYPE int  NOT NULL,
    ACCOUNT_AID int  NOT NULL,
    CONSTRAINT ACCOUNT_pk PRIMARY KEY  (ACCOUNT_AID)
);

-- Table: CITY
CREATE TABLE CITY (
    CITYNAME nvarchar(50)  NOT NULL,
    INFO nvarchar(max)  NULL,
    CONSTRAINT CITY_pk PRIMARY KEY  (CITYNAME)
);

-- Table: COMMENT
CREATE TABLE COMMENT (
    CMID int  NOT NULL,
    DATETIME datetime  NULL,
    CONTENT nvarchar(max)  NULL,
    ACCOUNT_AID int  NOT NULL,
	PLACE_NAME nvarchar(100)
    CONSTRAINT COMMENT_pk PRIMARY KEY  (CMID)
);

-- Table: PLACE
CREATE TABLE PLACE (
    PLACE_NAME nvarchar(100)  NOT NULL,
    CITY_CITYNAME nvarchar(50)  NOT NULL,
    DESCRIPTION nvarchar(max)  NOT NULL,
	NUMBER_OF_COMMENT int NOT NULL,
    CONSTRAINT PLACE_pk PRIMARY KEY  (PLACE_NAME)
);

-- Table: SCHEDULE
CREATE TABLE SCHEDULE (
    DATETIME datetime  NULL,
    GUIDE_INFO nvarchar(max)  NULL,
    SCHEDULE_ID int  NOT NULL,
	CONTENT nvarchar(max) NOT NULL,
    CONSTRAINT SCHEDULE_pk PRIMARY KEY  (SCHEDULE_ID)
);

-- Table: TOUR
CREATE TABLE TOUR (
    TOUR_TID int  NOT NULL,
    INFO nvarchar(max)  NOT NULL,
    DEPARTURE nvarchar(max)  NOT NULL,
    DESTINATION nvarchar(max)  NOT NULL,
    STARTTIME datetime  NOT NULL,
    DURATION nvarchar(max)  NOT NULL,
    FEE nvarchar(max)  NOT NULL,
	SCHEDULE_ID int  NOT NULL,
    CONSTRAINT TOUR_pk PRIMARY KEY  (TOUR_TID)
);

-- Table: TOUR_DETAIL
CREATE TABLE TOUR_DETAIL (
    TOUR_TID int  NOT NULL,
    CITY_CITYNAME nvarchar(50)  NOT NULL,
    CONSTRAINT TOUR_DETAIL_pk PRIMARY KEY  (TOUR_TID)
);

-- Table: TOUR_REGISTRATION
CREATE TABLE TOUR_REGISTRATION (
    ACT_STA int  NOT NULL,
    PAYMENT int  NOT NULL,
    REGISTIME datetime  NOT NULL,
    TOUR_TID int  NOT NULL,
    ACCOUNT_AID int  NOT NULL,
    CONSTRAINT TOUR_REGISTRATION_pk PRIMARY KEY  (TOUR_TID,ACCOUNT_AID)
);

-- foreign keys
-- Reference: COMMENT_ACCOUNT (table: COMMENT)
ALTER TABLE COMMENT ADD CONSTRAINT COMMENT_ACCOUNT
    FOREIGN KEY (ACCOUNT_AID)
    REFERENCES ACCOUNT (ACCOUNT_AID);


-- Reference: PLACE_CITY (table: PLACE)
ALTER TABLE PLACE ADD CONSTRAINT PLACE_CITY
    FOREIGN KEY (CITY_CITYNAME)
    REFERENCES CITY (CITYNAME);

-- Reference: PLACE_COMMENT (table: PLACE)
ALTER TABLE PLACE ADD CONSTRAINT PLACE_COMMENT
    FOREIGN KEY (PLACE_NAME)
    REFERENCES PLACE (PLACE_NAME);

-- Reference: TOUR_DETAIL_CITY (table: TOUR_DETAIL)
ALTER TABLE TOUR_DETAIL ADD CONSTRAINT TOUR_DETAIL_CITY
    FOREIGN KEY (CITY_CITYNAME)
    REFERENCES CITY (CITYNAME);

-- Reference: TOUR_DETAIL_TOUR (table: TOUR_DETAIL)
ALTER TABLE TOUR_DETAIL ADD CONSTRAINT TOUR_DETAIL_TOUR
    FOREIGN KEY (TOUR_TID)
    REFERENCES TOUR (TOUR_TID);

-- Reference: TOUR_REGISTRATION_ACCOUNT (table: TOUR_REGISTRATION)
ALTER TABLE TOUR_REGISTRATION ADD CONSTRAINT TOUR_REGISTRATION_ACCOUNT
    FOREIGN KEY (ACCOUNT_AID)
    REFERENCES ACCOUNT (ACCOUNT_AID);

-- Reference: TOUR_REGISTRATION_TOUR (table: TOUR_REGISTRATION)
ALTER TABLE TOUR_REGISTRATION ADD CONSTRAINT TOUR_REGISTRATION_TOUR
    FOREIGN KEY (TOUR_TID)
    REFERENCES TOUR (TOUR_TID);

-- Reference: TOUR_SCHEDULE (table:TOUR)
ALTER TABLE TOUR ADD CONSTRAINT TOUR_SCHEDULE
	FOREIGN KEY (SCHEDULE_ID)
	REFERENCES SCHEDULE (SCHEDULE_ID);

-- End of file.

drop table account
drop table city
drop table comment
drop table place
drop table SCHEDULE
drop table TOUR
drop table TOUR_DETAIL
drop table TOUR_REGISTRATION

